tunnel: prototype-resort-apps
credentials-file: /root/.cloudflared/9f8a5138-0c8e-4524-b6b8-287184532d72.json

# Ingress rules for routing traffic
ingress:
  # Backend API
  - hostname: prototype-resort-apps.okiabrian.my.id
    path: /api/
    service: http://localhost:8084
  # Backend health endpoint
  - hostname: prototype-resort-apps.okiabrian.my.id
    path: /health
    service: http://localhost:8084
  # Frontend application (Vite dev server) - catch-all for all other paths
  - hostname: prototype-resort-apps.okiabrian.my.id
    service: http://localhost:5173
  # Catch-all rule
  - service: http_status:404